import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { buildCompressedBlock, createCheckpoint, listCheckpoints, generateHandoffBlock } from '../context/compressor.js';
import { initContextDocs } from '../context/lifecycle.js';

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'tokenimizer-compressor-'));
}

function cleanup(dir: string): void {
  fs.rmSync(dir, { recursive: true, force: true });
}

describe('buildCompressedBlock', () => {
  let cwd: string;

  beforeEach(() => { cwd = tmpDir(); });
  afterEach(() => cleanup(cwd));

  it('returns a block with positive token count even with no context docs', () => {
    const { content, tokens } = buildCompressedBlock(cwd);
    expect(typeof content).toBe('string');
    expect(content.length).toBeGreaterThan(0);
    expect(tokens).toBeGreaterThan(0);
  });

  it('includes project summary when context is initialized', async () => {
    await initContextDocs(cwd);
    const { content } = buildCompressedBlock(cwd);
    expect(content).toContain('## Session Snapshot');
  });

  it('includes task status lines when progress.md has checkboxes', async () => {
    await initContextDocs(cwd);
    // Write a progress doc with real task content
    const progressPath = path.join(cwd, '.tokenimizer', 'context', 'progress.md');
    fs.writeFileSync(progressPath, '# Progress\n\n- [x] Task one\n- [ ] Task two\n');
    const { content } = buildCompressedBlock(cwd);
    expect(content).toContain('- [x] Task one');
  });

  it('always ends with a tokenimizer attribution line', () => {
    const { content } = buildCompressedBlock(cwd);
    expect(content).toContain('_Generated by tokenimizer');
  });
});

describe('createCheckpoint', () => {
  let cwd: string;

  beforeEach(() => { cwd = tmpDir(); });
  afterEach(() => cleanup(cwd));

  it('creates a snapshot file on disk', () => {
    const snap = createCheckpoint(cwd, 'test');
    const snapFile = path.join(cwd, '.tokenimizer', 'snapshots', `${snap.id}.md`);
    expect(fs.existsSync(snapFile)).toBe(true);
  });

  it('includes the label in the snapshot id', () => {
    const snap = createCheckpoint(cwd, 'my-label');
    expect(snap.id).toContain('my-label');
  });

  it('returns token count > 0', () => {
    const snap = createCheckpoint(cwd);
    expect(snap.tokens).toBeGreaterThan(0);
  });

  it('snapshot file contains tokenimizer header', () => {
    const snap = createCheckpoint(cwd, 'hdr-test');
    const content = fs.readFileSync(
      path.join(cwd, '.tokenimizer', 'snapshots', `${snap.id}.md`), 'utf8',
    );
    expect(content).toContain('tokenimizer snapshot');
  });
});

describe('listCheckpoints', () => {
  let cwd: string;

  beforeEach(() => { cwd = tmpDir(); });
  afterEach(() => cleanup(cwd));

  it('returns empty array when no snapshots exist', () => {
    expect(listCheckpoints(cwd)).toEqual([]);
  });

  it('returns created snapshots in reverse chronological order', () => {
    createCheckpoint(cwd, 'first');
    createCheckpoint(cwd, 'second');
    const snaps = listCheckpoints(cwd);
    expect(snaps.length).toBe(2);
    // Most recent first
    expect(snaps[0].id).toContain('second');
  });
});

describe('generateHandoffBlock', () => {
  let cwd: string;

  beforeEach(() => { cwd = tmpDir(); });
  afterEach(() => cleanup(cwd));

  it('starts with a New Session Handoff heading', () => {
    const { content } = generateHandoffBlock(cwd);
    expect(content).toContain('# New Session Handoff');
  });

  it('includes the compressed block content', () => {
    const { content: compressed } = buildCompressedBlock(cwd);
    const { content: handoff } = generateHandoffBlock(cwd);
    // Both should share the attribution footer
    expect(handoff).toContain('_Generated by tokenimizer');
  });
});
