import fs from 'fs';
import path from 'path';
import { writeAtomic, readOrNull, ensureDir } from '../utils/fs.js';
import { estimateTokens, formatTokens } from './tokenizer.js';
import { contextDocPath, listContextDocs } from './lifecycle.js';

const SNAPSHOTS_DIR = (cwd: string) => path.join(cwd, '.tokenimizer', 'snapshots');

export interface Snapshot {
  id:         string;
  createdAt:  string;
  tokens:     number;
  content:    string;
}

// ---------------------------------------------------------------------------
// Build a compact re-entry block from existing context docs
// ---------------------------------------------------------------------------

export function buildCompressedBlock(cwd: string): { content: string; tokens: number } {
  const sections: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  sections.push(`## Session Snapshot — ${date}`);
  sections.push('');

  // Pull project_summary (first 20 lines)
  const summaryPath = contextDocPath(cwd, 'project_summary.md');
  if (fs.existsSync(summaryPath)) {
    const lines = fs.readFileSync(summaryPath, 'utf8').split('\n').slice(0, 20).join('\n');
    sections.push('### Project');
    sections.push(lines.trim());
    sections.push('');
  }

  // Pull progress (tasks only — checkbox lines)
  const progressPath = contextDocPath(cwd, 'progress.md');
  if (fs.existsSync(progressPath)) {
    const content = fs.readFileSync(progressPath, 'utf8');
    const taskLines = content.split('\n')
      .filter(l => l.match(/^\s*-\s+\[[ xX]\]/))
      .slice(0, 20)
      .join('\n');
    if (taskLines) {
      sections.push('### Task Status');
      sections.push(taskLines);
      sections.push('');
    }
  }

  // Pull session summary (all of it — it's already compact)
  const sessionPath = contextDocPath(cwd, 'session_summary.md');
  if (fs.existsSync(sessionPath)) {
    const content = fs.readFileSync(sessionPath, 'utf8');
    // Strip the heading line
    const body = content.split('\n').slice(1).join('\n').trim();
    if (body && !body.includes('[fill in]')) {
      sections.push('### This Session');
      sections.push(body);
      sections.push('');
    }
  }

  // Pull current task
  const taskPath = contextDocPath(cwd, 'current_task.md');
  if (fs.existsSync(taskPath)) {
    const content = fs.readFileSync(taskPath, 'utf8');
    const body = content.split('\n').slice(1).join('\n').trim();
    if (body && !body.includes('[what you are working on')) {
      sections.push('### Current Task');
      sections.push(body);
      sections.push('');
    }
  }

  // Pull handoff if it has content
  const handoffPath = contextDocPath(cwd, 'handoff.md');
  if (fs.existsSync(handoffPath)) {
    const content = fs.readFileSync(handoffPath, 'utf8');
    const body = content.split('\n').slice(1).join('\n').trim();
    if (body && !body.includes('[summarize')) {
      sections.push('### Handoff Notes');
      sections.push(body);
      sections.push('');
    }
  }

  if (sections.length <= 2) {
    sections.push('_No context docs found. Run `tokenimizer context init` first._');
  }

  sections.push('---');
  sections.push('_Generated by tokenimizer context compressor._');
  sections.push('_Paste as first message of a new AI session to restore context at minimal token cost._');

  const content = sections.join('\n');
  return { content, tokens: estimateTokens(content) };
}

// ---------------------------------------------------------------------------
// Checkpoint — save a named snapshot
// ---------------------------------------------------------------------------

export function createCheckpoint(cwd: string, label?: string): Snapshot {
  ensureDir(SNAPSHOTS_DIR(cwd));

  const { content, tokens } = buildCompressedBlock(cwd);
  const id        = `${Date.now()}${label ? `-${label.replace(/[^a-z0-9]/gi, '-').toLowerCase()}` : ''}`;
  const createdAt = new Date().toISOString();
  const snapshot  = { id, createdAt, tokens, content };

  writeAtomic(
    path.join(SNAPSHOTS_DIR(cwd), `${id}.md`),
    [
      `<!-- tokenimizer snapshot: ${id} | ${createdAt} | ~${tokens} tokens -->`,
      '',
      content,
    ].join('\n'),
  );

  return snapshot;
}

// ---------------------------------------------------------------------------
// List checkpoints
// ---------------------------------------------------------------------------

export function listCheckpoints(cwd: string): Array<{ id: string; tokens: number; createdAt: string; file: string }> {
  const dir = SNAPSHOTS_DIR(cwd);
  if (!fs.existsSync(dir)) return [];

  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .sort()
    .reverse()
    .map(f => {
      const file    = path.join(dir, f);
      const content = fs.readFileSync(file, 'utf8');
      const meta    = content.match(/<!-- tokenimizer snapshot: ([^\s|]+) \| ([^\s|]+) \| ~(\d+) tokens -->/);
      return {
        id:        meta?.[1] ?? f.replace('.md', ''),
        createdAt: meta?.[2] ?? '?',
        tokens:    meta ? parseInt(meta[3], 10) : estimateTokens(content),
        file,
      };
    })
    .slice(0, 20);
}

// ---------------------------------------------------------------------------
// Handoff block — optimized for pasting into new session
// ---------------------------------------------------------------------------

export function generateHandoffBlock(cwd: string): { content: string; tokens: number } {
  const { content: compressed, tokens } = buildCompressedBlock(cwd);
  const handoff = [
    '# New Session Handoff',
    '',
    '> Paste this block as your FIRST message in the new AI session.',
    '> It contains compressed context from the previous session.',
    '',
    compressed,
  ].join('\n');
  return { content: handoff, tokens: estimateTokens(handoff) };
}
