import fs from 'fs';
import path from 'path';
import glob from 'fast-glob';
import { writeAtomic, readOrNull, ensureDir } from '../utils/fs.js';
import { estimateTokens } from './tokenizer.js';

export interface LifecycleDocs {
  projectSummary:  string;
  architecture:    string;
  sessionSummary:  string;
  progress:        string;
  handoff:         string;
  currentTask:     string;
}

const CONTEXT_DIR = (cwd: string) => path.join(cwd, '.tokenimizer', 'context');

export function contextDocPath(cwd: string, name: string): string {
  return path.join(CONTEXT_DIR(cwd), name);
}

// ---------------------------------------------------------------------------
// project_summary.md — ~500 token target
// ---------------------------------------------------------------------------

async function generateProjectSummary(cwd: string): Promise<string> {
  const pkgPath = path.join(cwd, 'package.json');
  const readmePath = [
    path.join(cwd, 'README.md'),
    path.join(cwd, 'readme.md'),
    path.join(cwd, 'README'),
  ].find(p => fs.existsSync(p));

  let name    = path.basename(cwd);
  let version = '';
  let desc    = '';
  let scripts = '';

  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
      name    = pkg.name ?? name;
      version = pkg.version ? `v${pkg.version}` : '';
      desc    = pkg.description ?? '';
      const s = pkg.scripts ?? {};
      scripts = Object.entries(s).slice(0, 6)
        .map(([k, v]) => `  ${k}: ${v}`)
        .join('\n');
    } catch { /* ignore */ }
  }

  let readmeExcerpt = '';
  if (readmePath) {
    const lines = fs.readFileSync(readmePath, 'utf8').split('\n').slice(0, 30);
    readmeExcerpt = lines.join('\n');
  }

  // Folder structure (top 2 levels, ignoring noise)
  const IGNORE = ['node_modules', '.git', 'dist', '.tokenimizer', 'coverage', '.next', 'build'];
  const topItems = fs.readdirSync(cwd)
    .filter(f => !IGNORE.includes(f) && !f.startsWith('.'))
    .slice(0, 20);

  const structure = topItems.map(item => {
    const full = path.join(cwd, item);
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      const children = fs.readdirSync(full)
        .filter(f => !IGNORE.includes(f) && !f.startsWith('.'))
        .slice(0, 8)
        .join(', ');
      return `  ${item}/  (${children})`;
    }
    return `  ${item}`;
  }).join('\n');

  const lines = [
    `# Project Summary — ${name} ${version}`,
    '',
    desc ? `**Purpose:** ${desc}` : '',
    '',
    readmeExcerpt ? `## Overview\n${readmeExcerpt}` : '',
    '',
    `## Structure\n${structure}`,
    '',
    scripts ? `## Key Scripts\n${scripts}` : '',
    '',
    `_Generated by tokenimizer on ${new Date().toISOString().split('T')[0]}_`,
  ].filter(l => l !== undefined).join('\n').trim();

  return lines;
}

// ---------------------------------------------------------------------------
// architecture.md — ~1000 token target
// ---------------------------------------------------------------------------

async function generateArchitecture(cwd: string): Promise<string> {
  const IGNORE_DIRS = ['node_modules', '.git', 'dist', '.tokenimizer', 'coverage', '.next', 'build'];

  // Find source directories
  const sourceFiles = await glob(['src/**/*.{ts,js,tsx,jsx}', '*.{ts,js}'], {
    cwd,
    ignore: IGNORE_DIRS.map(d => `**/${d}/**`),
    onlyFiles: true,
    deep: 4,
  });

  // Group by directory
  const byDir: Record<string, string[]> = {};
  for (const f of sourceFiles.slice(0, 80)) {
    const dir = path.dirname(f);
    byDir[dir] = byDir[dir] ?? [];
    byDir[dir].push(path.basename(f));
  }

  const dirLines = Object.entries(byDir)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([dir, files]) => `  ${dir}/\n    ${files.join(', ')}`)
    .join('\n');

  // Config files present
  const configFiles = [
    'tsconfig.json', 'package.json', '.eslintrc.json', '.eslintrc.js',
    'vite.config.ts', 'next.config.js', 'next.config.ts',
    'tailwind.config.js', 'tailwind.config.ts', 'Dockerfile',
    '.env.example', 'docker-compose.yml',
  ].filter(f => fs.existsSync(path.join(cwd, f)));

  const lines = [
    `# Architecture — ${path.basename(cwd)}`,
    '',
    '## Source Layout',
    dirLines || '  (no source files detected)',
    '',
    configFiles.length ? `## Config Files Present\n  ${configFiles.join(', ')}` : '',
    '',
    `_Generated by tokenimizer on ${new Date().toISOString().split('T')[0]}_`,
  ].filter(l => l !== undefined).join('\n').trim();

  return lines;
}

// ---------------------------------------------------------------------------
// Templates for session docs
// ---------------------------------------------------------------------------

function generateSessionSummary(): string {
  return [
    `# Session Summary — ${new Date().toISOString().split('T')[0]}`,
    '',
    '**What was worked on this session:**',
    '- [fill in]',
    '',
    '**Decisions made:**',
    '- [fill in]',
    '',
    '**Current state:**',
    '- [what works]',
    '- [what is broken or incomplete]',
    '',
    '**Blockers:**',
    '- [none | describe]',
    '',
    '_Update this file during your session. Run `tokenimizer checkpoint` to snapshot._',
  ].join('\n');
}

function generateProgress(): string {
  return [
    `# Progress — ${new Date().toISOString().split('T')[0]}`,
    '',
    '## In Progress',
    '- [ ] [current task]',
    '',
    '## Done',
    '- [x] [completed task]',
    '',
    '## Backlog',
    '- [ ] [future task]',
    '',
    '_Keep this file updated as tasks complete._',
  ].join('\n');
}

function generateHandoff(cwd: string): string {
  const projectSummaryExists = fs.existsSync(contextDocPath(cwd, 'project_summary.md'));
  const architectureExists   = fs.existsSync(contextDocPath(cwd, 'architecture.md'));
  const progressExists       = fs.existsSync(contextDocPath(cwd, 'progress.md'));

  return [
    `# Handoff — ${new Date().toISOString().split('T')[0]}`,
    '',
    '> Paste this file as the first message of a new AI session to restore context.',
    '',
    '## Project',
    projectSummaryExists
      ? '_See .tokenimizer/context/project_summary.md_'
      : '**Name:** [project name]  \n**Purpose:** [one sentence]  \n**Stack:** [key tech]',
    '',
    '## What Was Done',
    '- [summarize the last session]',
    '',
    '## Current State',
    '- [what works now]',
    '- [what is incomplete]',
    '',
    '## Next Step',
    '[The single most important next action]',
    '',
    progressExists ? '_See .tokenimizer/context/progress.md for full task list._' : '',
    architectureExists ? '_See .tokenimizer/context/architecture.md for project structure._' : '',
    '',
    '_Generated by tokenimizer. Edit before pasting to fill in the blanks._',
  ].filter(l => l !== undefined).join('\n').trim();
}

function generateCurrentTask(): string {
  return [
    `# Current Task — ${new Date().toISOString().split('T')[0]}`,
    '',
    '**Task:** [what you are working on right now]',
    '',
    '**Goal:** [what done looks like]',
    '',
    '**Files involved:**',
    '- [file path]',
    '',
    '**Approach:**',
    '[how you plan to do it]',
    '',
    '_Update this file at the start of each task. Keeps context tight for the AI._',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface InitResult {
  created: string[];
  skipped: string[];
  tokens:  Record<string, number>;
}

export async function initContextDocs(cwd: string, force = false): Promise<InitResult> {
  const dir = CONTEXT_DIR(cwd);
  ensureDir(dir);

  const created: string[] = [];
  const skipped: string[] = [];
  const tokens:  Record<string, number> = {};

  const docs: Array<{ name: string; generate: () => Promise<string> | string }> = [
    { name: 'project_summary.md', generate: () => generateProjectSummary(cwd) },
    { name: 'architecture.md',    generate: () => generateArchitecture(cwd) },
    { name: 'session_summary.md', generate: () => generateSessionSummary() },
    { name: 'progress.md',        generate: () => generateProgress() },
    { name: 'handoff.md',         generate: () => generateHandoff(cwd) },
    { name: 'current_task.md',    generate: () => generateCurrentTask() },
  ];

  for (const doc of docs) {
    const filePath = contextDocPath(cwd, doc.name);
    if (!force && fs.existsSync(filePath)) {
      skipped.push(doc.name);
      continue;
    }
    const content = await doc.generate();
    writeAtomic(filePath, content + '\n');
    tokens[doc.name] = estimateTokens(content);
    created.push(doc.name);
  }

  return { created, skipped, tokens };
}

export async function refreshContextDocs(cwd: string): Promise<InitResult> {
  // Only regenerate the auto-generated ones (not session/progress/current_task — user-maintained)
  const dir = CONTEXT_DIR(cwd);
  ensureDir(dir);

  const created: string[] = [];
  const skipped: string[] = [];
  const tokens:  Record<string, number> = {};

  const autoDocs: Array<{ name: string; generate: () => Promise<string> | string }> = [
    { name: 'project_summary.md', generate: () => generateProjectSummary(cwd) },
    { name: 'architecture.md',    generate: () => generateArchitecture(cwd) },
    { name: 'handoff.md',         generate: () => generateHandoff(cwd) },
  ];

  for (const doc of autoDocs) {
    const filePath = contextDocPath(cwd, doc.name);
    const content  = await doc.generate();
    writeAtomic(filePath, content + '\n');
    tokens[doc.name] = estimateTokens(content);
    created.push(doc.name);
  }

  return { created, skipped, tokens };
}

export function listContextDocs(cwd: string): Array<{ name: string; tokens: number; exists: boolean }> {
  const names = [
    'project_summary.md',
    'architecture.md',
    'session_summary.md',
    'progress.md',
    'handoff.md',
    'current_task.md',
  ];
  return names.map(name => {
    const filePath = contextDocPath(cwd, name);
    const content  = readOrNull(filePath);
    return {
      name,
      exists: content !== null,
      tokens: content ? estimateTokens(content) : 0,
    };
  });
}
